import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { randomBytes } from 'node:crypto';

/*
 * File storage behind one small interface, so business code never knows
 * where bytes live. Today: a folder on the local disk (development). An
 * object-storage driver (S3-compatible) can be added by implementing
 * FileStorage and selecting it with STORAGE_DRIVER — nothing else changes.
 *
 * Keys are generated by the application (never taken from a user's file
 * name) and are never shown to users; files are served through
 * permission-checked routes by document id.
 */

export interface FileStorage {
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  /** The stored bytes, or null if the object doesn't exist. */
  get(key: string): Promise<Buffer | null>;
}

const KEY_PATTERN = /^[a-z0-9][a-z0-9/_.-]{0,300}$/;

function assertKey(key: string) {
  if (!KEY_PATTERN.test(key) || key.includes('..') || key.includes('//')) {
    throw new Error('Invalid storage key.');
  }
}

/** Development storage: files under LOCAL_STORAGE_DIR (default ./.local-storage, git-ignored). */
class LocalDiskStorage implements FileStorage {
  constructor(private readonly root: string) {}

  private pathFor(key: string) {
    assertKey(key);
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep)) throw new Error('Invalid storage key.');
    return full;
  }

  async put(key: string, bytes: Buffer) {
    const full = this.pathFor(key);
    await mkdir(path.dirname(full), { recursive: true });
    // Write to a temporary name first so a half-written file is never served.
    const temporary = `${full}.${randomBytes(6).toString('hex')}.tmp`;
    await writeFile(temporary, bytes);
    await rename(temporary, full);
  }

  async get(key: string) {
    try {
      return await readFile(this.pathFor(key));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    }
  }
}

let storage: FileStorage | null = null;

export function getStorage(): FileStorage {
  if (storage) return storage;
  const driver = process.env.STORAGE_DRIVER ?? 'local';
  if (driver !== 'local') {
    throw new Error(`Storage driver "${driver}" is not available yet. Use STORAGE_DRIVER=local.`);
  }
  storage = new LocalDiskStorage(process.env.LOCAL_STORAGE_DIR ?? path.join(process.cwd(), '.local-storage'));
  return storage;
}

export type ImageType = { mimeType: 'image/jpeg' | 'image/png' | 'image/webp'; extension: 'jpg' | 'png' | 'webp' };

/** The image type from the file's actual bytes (magic numbers) — never from its name or declared type. */
export function sniffImage(bytes: Buffer): ImageType | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return { mimeType: 'image/jpeg', extension: 'jpg' };
  if (bytes.length >= 8 && bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
    return { mimeType: 'image/png', extension: 'png' };
  }
  if (bytes.length >= 12 && bytes.subarray(0, 4).toString('latin1') === 'RIFF' && bytes.subarray(8, 12).toString('latin1') === 'WEBP') {
    return { mimeType: 'image/webp', extension: 'webp' };
  }
  return null;
}
